Revert "Merge pull request #4 from kyoto-kaira/revert-3-miyamae/refac…
kyoto-kaira/syllabus-search-RAG pull request #5
Opened 2024-10-30 07:41 UTC by nabecha

…tor"

This reverts commit 42ccc3d0129f6e68bb8f6fc3b754d07c0953cc62, reversing changes made to 9173983f71b42565ef4c3af511b37a0d297cdad1.

2024-10-30 08:00 UTC, matsuda-tkm reviewed
気になる箇所たくさんありますが、すぐコメントできるところはしました！
また時間空いた時に追加でコメントします。

最も気になる点としては、データをすべてpklで管理している点です。
pklは最終手段で、基本的には.jsonや.txtなどのプレーンテキストファイルを用いましょう。pickleはバイナリなので中身が直接見えず、レビューやデバッグがしづらいです。

2024-10-30 08:00 UTC, matsuda-tkm commented on app.py
> +    yojigen = pickle.load(f)
バックスラッシュではなくスラッシュにしてください
```suggestion
path1 = 'data2/shirabasu_classtype.pkl'
with open(path1, 'rb') as f:
    classtypes = pickle.load(f)
path2 = 'data2/shirabasu_departments.pkl'
with open(path2, 'rb') as f:
    departments = pickle.load(f)
path3 = 'data2/shirabasu_fulltexts.pkl'
with open(path3, 'rb') as f:
    fulltexts = pickle.load(f)
path4 = 'data2/shirabasu_hyoka.pkl'
with open(path4, 'rb') as f:
    hyoka = pickle.load(f)
path5 = 'data2/shirabasu_keywordtexts.pkl'
with open(path5, 'rb') as f:
    keywordtexts = pickle.load(f)
path6 = 'data2/shirabasu_metadatas.pkl'
with open(path6, 'rb') as f:
    metadatas = pickle.load(f)
path7 = 'data2/shirabasu_texts.pkl'
with open(path7, 'rb') as f:
    texts = pickle.load(f)
path8 = 'data2/shirabasu_yojigen.pkl'
with open(path8, 'rb') as f:
    yojigen = pickle.load(f)

```

2024-10-30 08:00 UTC, matsuda-tkm commented on app.py
> +os.environ['GOOGLE_API_KEY'] = '------------------------'
ミスってAPIキーをpushしてしまう恐れがあるので直書きするようなコードはやめましょう。
なので、この行を削除し、環境変数GOOGLE_API_KEYはコマンドで設定しましょう。Windowsの場合は以下

```shell
set GOOGLE_API_KEY=--------------------
```

設定した環境変数を確認する場合は以下
```shell
echo %GOOGLE_API_KEY%
```

2024-10-30 08:00 UTC, matsuda-tkm commented on app.py
> +    yojigen = pickle.load(f)
streamlitのキャッシュ機能があるので、読み込んだデータはこちらに入れてください。
そうすれば、検索ボックスを編集した時に数秒固まる現象を解消できます

2024-10-30 08:00 UTC, matsuda-tkm commented on preprocess.py
> +        l = ['月1','月2','月3','火1','火2','火3','水1','水2','水3','木1','木2','木3']
ここあってます？

2024-10-30 08:00 UTC, matsuda-tkm commented on preprocess.py
> +            l.append('金5')
さすがに見栄え悪いのでforループ使いましょう。笑

2024-10-30 08:00 UTC, matsuda-tkm commented on preprocess.py
> +from bs4 import BeautifulSoup
import文はファイルの先頭に持ってくるべきです！

2024-10-30 08:00 UTC, matsuda-tkm commented on preprocess.py
> +    html = html.replace('０','0').replace('１','1').replace('２','2').replace('３','3').replace('４','4').replace('５','5').replace('６','6').replace('７','7').replace('８','8').replace('９','9')
```suggestion
zenkaku_to_hankaku = str.maketrans('０１２３４５６７８９', '0123456789')
html = html.translate(zenkaku_to_hankaku)
```
こういう書き方できますよ

2024-10-30 08:01 UTC, matsuda-tkm commented on preprocess.py
> +from bs4 import BeautifulSoup
他のファイルも同様です！

2024-11-02 09:12 UTC, nabecha commented
言われたところは修正しました

2024年10月30日(水) 17:01 Matsuda Takumi ***@***.***>:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In preprocess.py
> <https://github.com/kyoto-kaira/syllabus-search-RAG/pull/5#discussion_r1822065442>
> :
>
> > +def class_type(d):
> +    if '授業形態' in d.keys():
> +        if d['授業形態'] == '特殊講義':
> +            d['授業形態'] = ['特殊講義']
> +        else:
> +            l = []
> +            for text in ['講義','演習','実習','実験','語学','講読','卒業研究','ゼミナール']:
> +                if text in d['授業形態']:
> +                    l.append(text)
> +            d['授業形態'] = l
> +        return d
> +    else:
> +        d['授業形態'] = []
> +        return d
> +
> +from bs4 import BeautifulSoup
>
> 他のファイルも同様です！
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kyoto-kaira/syllabus-search-RAG/pull/5#discussion_r1822065442>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6J45XBMZOSHPW5JTN2XFN3Z6CG63AVCNFSM6AAAAABQ3NG5PSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIMBTHEYDKNJYGY>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2024-11-02 10:05 UTC, matsuda-tkm commented
動作上は問題ないですが以下のwarningが出るので、解消したいです（たぶんimport変えればなんとかなるはず）
```
/Users/takumi/github/nf2024/tmp/syllabus-search-RAG/app.py:5: LangChainDeprecationWarning: Importing HuggingFaceEmbeddings from langchain.embeddings is deprecated. Please replace deprecated imports:

>> from langchain.embeddings import HuggingFaceEmbeddings

with new imports of:

>> from langchain_community.embeddings import HuggingFaceEmbeddings
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here <https://python.langchain.com/docs/versions/v0_2/>
  from langchain.embeddings import HuggingFaceEmbeddings
/Users/takumi/github/nf2024/tmp/syllabus-search-RAG/app.py:6: LangChainDeprecationWarning: Importing FAISS from langchain.vectorstores is deprecated. Please replace deprecated imports:

>> from langchain.vectorstores import FAISS

with new imports of:

>> from langchain_community.vectorstores import FAISS
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here <https://python.langchain.com/docs/versions/v0_2/>
  from langchain.vectorstores import FAISS
/Users/takumi/github/nf2024/tmp/syllabus-search-RAG/app.py:42: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFaceEmbeddings``.
  embedding = HuggingFaceEmbeddings(model_name="intfloat/multilingual-e5-base")
2024-11-02 18:19:14.571 Examining the path of torch.classes raised: Tried to instantiate class '__path__._path', but it does not exist! Ensure that it is registered via torch::class_
2024-11-02 18:19:50.118 Examining the path of torch.classes raised: Tried to instantiate class '__path__._path', but it does not exist! Ensure that it is registered via torch::class_
```

2024-11-02 10:12 UTC, matsuda-tkm commented
変数名やファイル名に、日本語のローマ字つかっているところがあるので直してもらえると...（特にshirabasuが気になるｗ）

こちら1度目を通しておいてください！
- https://zenn.dev/naoki_oshiumi/articles/aad7e1b3719fad
- https://pep8-ja.readthedocs.io/ja/latest/

2024-11-19 03:20 UTC, matsuda-tkm commented
時間もないのでこちら松田が巻き取ります

2024-11-19 03:32 UTC, nabecha commented
すいません。すっかり忘れていました。午後から授業があるので、午後7時から8時までには修正します。時間的に問題ないのなら修正させてください。

2024年11月19日(火) 12:21 Matsuda Takumi ***@***.***>:

> 時間もないのでこちら松田が巻き取ります
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kyoto-kaira/syllabus-search-RAG/pull/5#issuecomment-2484625005>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6J45XECUUAHZIYSNWK2GI32BKVCFAVCNFSM6AAAAABQ3NG5PSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIOBUGYZDKMBQGU>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2024-11-19 03:48 UTC, matsuda-tkm commented
あ、わかりました
まず作業する前にpullしてください。そうしないとpushしたときに怒られてめんどくさくなります

```shell
git pull
```

さっきディレクトリを整理しました。

- db→データはここに入れる
- src→app.py以外のコードはここに入れる
    - src/modules→アプリケーション関連のコードはここに入れる
    - src/preprocess→DBを作るときなどに使ったコードはここに入れる
- app.py→streamlitのアプリ本体
- requirements.txt→動かすのに必要なライブラリを記載（バージョン指定は書かなくて良い）
- requirements-dev.txt→いじらない

仮想環境つくってrequirements.txt, requirements-dev.txtをpip installする運用です

2024-11-19 03:51 UTC, nabecha commented
承知しました

2024年11月19日(火) 12:49 Matsuda Takumi ***@***.***>:

> あ、わかりました
> まず作業する前にpullしてください。そうしないとpushしたときに怒られてめんどくさくなります
>
> git pull
>
> さっきディレクトリを整理しました。
>
>    - db→データはここに入れる
>    - src→app.py以外のコードはここに入れる
>       - src/modules→アプリケーション関連のコードはここに入れる
>       - src/preprocess→DBを作るときなどに使ったコードはここに入れる
>    - app.py→streamlitのアプリ本体
>    - requirements.txt→動かすのに必要なライブラリを記載（バージョン指定は書かなくて良い）
>    - requirements-dev.txt→いじらない
>
> 仮想環境つくってrequirements.txt, requirements-dev.txtをpip installする運用です
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kyoto-kaira/syllabus-search-RAG/pull/5#issuecomment-2484649196>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6J45XELF5BPVHY64JOKYOT2BKYMDAVCNFSM6AAAAABQ3NG5PSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIOBUGY2DSMJZGY>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2024-11-19 05:25 UTC, matsuda-tkm commented
以前モックを作ったことがあって、検索結果の表示はこんなイメージでお願いします！

- 参考：https://github.com/kyoto-kaira/syllabus-search-RAG/blob/matsuda/%232_streamlit/app.py

https://github.com/user-attachments/assets/75eddabe-9243-4235-b7e0-838d68dac695

2024-11-19 08:23 UTC, nabecha commented
すいません。pushされたgithubをpcにiみzむにはどうしたらよいのでしょうか。

________________________________
差出人: Matsuda Takumi ***@***.***>
送信日r: 2024年11月19日 5:26
宛先: kyoto-kaira/syllabus-search-RAG ***@***.***>
CC: Miyamae ***@***.***>; Assign ***@***.***>
件名: Re: [kyoto-kaira/syllabus-search-RAG] Revert "Merge pull request #4 from kyoto-kaira/revert-3-miyamae/refac… (PR #5)


以前モックを作ったことがあって、仕鹘Y果の表示はこんなイメ`ジでおいします！

  *   参考：https://github.com/kyoto-kaira/syllabus-search-RAG/blob/matsuda/%232_streamlit/app.py

https://github.com/user-attachments/assets/75eddabe-9243-4235-b7e0-838d68dac695

―
Reply to this email directly, view it on GitHub<https://github.com/kyoto-kaira/syllabus-search-RAG/pull/5#issuecomment-2484737644>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A6J45XGLF67PKAIA7AJE5F32BLDXTAVCNFSM6AAAAABQ3NG5PSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIOBUG4ZTONRUGQ>.
You are receiving this because you were assigned.Message ID: ***@***.***>

2024-11-19 08:29 UTC, matsuda-tkm commented
syllabus-search-RAGのディレクトリに移動して、
git checkout miyame/refactor
git pull
です

2024-11-19 08:46 UTC, nabecha commented
ディレクトリに移婴工毪长趣稀git clone http......
とすることですか。

________________________________
差出人: Matsuda Takumi ***@***.***>
送信日r: 2024年11月19日 8:30
宛先: kyoto-kaira/syllabus-search-RAG ***@***.***>
CC: Miyamae ***@***.***>; Assign ***@***.***>
件名: Re: [kyoto-kaira/syllabus-search-RAG] Revert "Merge pull request #4 from kyoto-kaira/revert-3-miyamae/refac… (PR #5)


syllabus-search-RAGのディレクトリに移婴筏啤
git checkout miyame/refactor
git pull
です

―
Reply to this email directly, view it on GitHub<https://github.com/kyoto-kaira/syllabus-search-RAG/pull/5#issuecomment-2485022389>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A6J45XGLFQ3UQWVGI3JUWHD2BLZJVAVCNFSM6AAAAABQ3NG5PSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIOBVGAZDEMZYHE>.
You are receiving this because you were assigned.Message ID: ***@***.***>

2024-11-19 09:01 UTC, matsuda-tkm commented
いままで作業していたディレクトリ消しちゃいました？
それなら任意の場所でgit clone https://....してください

2024-11-19 09:20 UTC, nabecha commented
git clone https:..
cd syllabus-search-RAG
git checkout miyame/refactor
とした後で、
PS G:\マイドライブ\新しいフォルダ`\syllabus-search-RAG> git pull miyamae/refactor
fatal: 'miyamae/refactor' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
このようなエラ`が出ます

________________________________
差出人: Matsuda Takumi ***@***.***>
送信日r: 2024年11月19日 9:01
宛先: kyoto-kaira/syllabus-search-RAG ***@***.***>
CC: Miyamae ***@***.***>; Assign ***@***.***>
件名: Re: [kyoto-kaira/syllabus-search-RAG] Revert "Merge pull request #4 from kyoto-kaira/revert-3-miyamae/refac… (PR #5)


いままで作Iしていたディレクトリ消しちゃいました？
それなら任意の鏊git clone https://....してください

―
Reply to this email directly, view it on GitHub<https://github.com/kyoto-kaira/syllabus-search-RAG/pull/5#issuecomment-2485088981>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A6J45XFQ4DHGZE3UYAKIVR32BL46FAVCNFSM6AAAAABQ3NG5PSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIOBVGA4DQOJYGE>.
You are receiving this because you were assigned.Message ID: ***@***.***>

2024-11-19 09:51 UTC, nabecha commented
ブランチを指定するのにgit fetchを使うと以下のようなエラ`になります。
The authenticity of host 'github.com (20.27.177.113)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
***@***.***: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

モックのコ`ドをどこかに保存して、マ`ジしても}ないと思うので、マ`ジしてロ`カルにiみzんでも良いのではないでしょうか。

________________________________
差出人: m前明生 ***@***.***>
送信日r: 2024年11月19日 9:20
宛先: kyoto-kaira/syllabus-search-RAG ***@***.***>
件名: Re: [kyoto-kaira/syllabus-search-RAG] Revert "Merge pull request #4 from kyoto-kaira/revert-3-miyamae/refac… (PR #5)

git clone https:..
cd syllabus-search-RAG
git checkout miyame/refactor
とした後で、
PS G:\マイドライブ\新しいフォルダ`\syllabus-search-RAG> git pull miyamae/refactor
fatal: 'miyamae/refactor' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
このようなエラ`が出ます

________________________________
差出人: Matsuda Takumi ***@***.***>
送信日r: 2024年11月19日 9:01
宛先: kyoto-kaira/syllabus-search-RAG ***@***.***>
CC: Miyamae ***@***.***>; Assign ***@***.***>
件名: Re: [kyoto-kaira/syllabus-search-RAG] Revert "Merge pull request #4 from kyoto-kaira/revert-3-miyamae/refac… (PR #5)


いままで作Iしていたディレクトリ消しちゃいました？
それなら任意の鏊git clone https://....してください

―
Reply to this email directly, view it on GitHub<https://github.com/kyoto-kaira/syllabus-search-RAG/pull/5#issuecomment-2485088981>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A6J45XFQ4DHGZE3UYAKIVR32BL46FAVCNFSM6AAAAABQ3NG5PSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIOBVGA4DQOJYGE>.
You are receiving this because you were assigned.Message ID: ***@***.***>

2024-11-19 10:01 UTC, matsuda-tkm commented
```
git clone https:.....
cd syllabus-serach-RAG
git checkout miyamae/refactor
```
まで成功しているならそれで問題ないです（最新のコードが反映されている）


あとなぜか文字化けしちゃってるのでGitHub上で返信していただけますか？
<img width="1413" alt="image" src="https://github.com/user-attachments/assets/4aa35ec8-937c-4c78-a926-9535e31e46e4">

2024-11-19 10:24 UTC, nabecha commented
最新のコーデではなく、mainのコードしか表示されません

2024-11-20 08:09 UTC, nabecha commented
![image](https://github.com/user-attachments/assets/a5929b9f-8ae9-47d0-b417-3d46b21d0027)

2024-11-20 08:13 UTC, nabecha commented
・要約を生成しているときは、シラバス要約生成中...と表示されます。
・バージョンをrequirementsにまとめました
・

2024-11-20 09:27 UTC, matsuda-tkm requested changes

2024-11-20 09:27 UTC, matsuda-tkm commented on requirements.txt
> +google-generativeai==0.8.3
sentence-transformers
faiss-cpu
が足りなかったです
追加お願いします！

2024-11-20 09:27 UTC, matsuda-tkm commented on app.py
> +                        st.text(result_str)
st.textだとプレーンテキスト表示になってしまうので、Markdownになるように表示させてください！
```suggestion
                        st.markdown(result_str)

```

2024-11-20 09:27 UTC, matsuda-tkm commented on app.py
> +                st.text(a[i].metadata["科目名"] + "   URL:" + a[i].metadata["URL"])
link_buttonを使ってください！
https://docs.streamlit.io/develop/api-reference/widgets/st.link_button

```suggestion
                st.link_button(label=a[i].metadata["科目名"], url= a[i].metadata["URL"])
```

2024-11-20 09:27 UTC, matsuda-tkm commented on app.py
> +                st.text(a[i].metadata["科目名"] + "   URL:" + a[i].metadata["URL"])
```suggestion
            st.write("該当する科目は以下の通りです。")
            # 検索した科目を列挙する
            for i in range(len(a)):
                st.write(a[i].metadata["科目名"] + "   URL:" + a[i].metadata["URL"])

```

2024-11-20 09:27 UTC, matsuda-tkm commented on app.py
> +            a = store.similarity_search(query, k=int(k))
できれば、similarity_searchかmax_marginal_relevance_searchを選べるようにして欲しいです

2024-11-20 10:35 UTC, matsuda-tkm requested changes
下記のようになっている場合がありました

```markdown
* 所属部局、職名、氏名:  情報学研究科准教授後藤幸織情報学研究科教授西田眞也情報学研究科教授熊田孝恒
```

2024-11-20 10:43 UTC, nabecha commented
所属部局、職名、氏名は空白が入るようにmetadata前処理を変更しましたが、埋め込み時にmetadata指定していませんでした。

2024-11-20 12:16 UTC, nabecha commented
![image](https://github.com/user-attachments/assets/4fa57c32-0441-49bd-b208-5421d4c5309c)

2024-11-20 12:22 UTC, nabecha commented
sentence-transformers
faiss-cpu
の他にfaiss-gpu、streamlit-pillsを追加しました。

2024-11-20 13:24 UTC, matsuda-tkm commented
faiss-gpuは不要なので削除お願いします

こちらにデプロイしています
https://ku-syllabus-search-rag.streamlit.app/

2024-11-20 13:36 UTC, matsuda-tkm approved these changes
ありがとうございます！無事動きました。
いったんこのPRはマージしてcloseしようと思います。

2024-11-20 13:37 UTC, merged

2024-11-20 13:40 UTC, matsuda-tkm commented
宮前さんの方で触ってみながら気になるところをどんどん改善していってください。
この後変更する場合は以下のようにしてから作業してください！

```shell
git checkout main
git pull  # (失敗したら以前ハドルした時のように編集を破棄する)
git checkout -b fix/xxxx  # xxxxは修正内容がわかるような単語
```